version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    container_name: db
    restart: always
    ports:
      - 5434:5432
    command: postgres -c stats_temp_directory=/tmp
    volumes:
      - "associ-db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=${postgres_user}
      - POSTGRES_PASSWORD=${postgres_pwd}
      - POSTGRES_DB=${postgres_db}
volumes:
  associ-db:
    external: true
