import Head from "next/head";
import Navbar from "../Nav";
import Footer from "../Information/Footer";

interface UnauthurizedProps {
  message?: string;
}

const Unauthurized = ({ message }: UnauthurizedProps) => {
  return (
    <>
      <Head>
        <title>สมาคมอนุรักษ์ และพัฒนาควายไทย</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="flex min-h-screen w-full items-center justify-center">
        <div className="text-3xl">{message}</div>
      </div>
      <Footer />
    </>
  );
};

export default Unauthurized;
