import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import FarmMenu from "~/components/Farm/FarmMenu";
import FarmTable from "~/components/Farm/FarmTable";
import Navbar from "~/components/Nav";
import { useBitkubNext } from "~/contexts/bitkubNextContext";

const MyFarm = () => {
  const { replace } = useRouter();
  const { isConnected } = useBitkubNext();

  if (!isConnected) {
    void replace("/");
  }

  return (
    <>
      <Head>
        <title>สมาคมอนุรักษ์ และพัฒนาควายไทย</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="mt-[90px] h-[90vh] w-full">
        <div className="grid grid-cols-1 gap-2 px-2 xl:px-10">
          <div className="place-self-end">
            <FarmMenu />
          </div>
          <FarmTable />
        </div>
      </div>
    </>
  );
};

export default MyFarm;
