import React from 'react';
import Head from 'next/head';
import Navbar from '~/components/Nav';
import { useRouter } from 'next/router';
import Link from 'next/link';

const Success = () => {
  const { query, replace } = useRouter();

  return (
  <>
      <Head>
        <title>สมาคมอนุรักษ์ และพัฒนาควายไทย</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="mt-[25vh] w-full flex justify-center">
        <div className="card w-96 shadow max-w-md">
          <div className="card-body items-center">
            <h1 className="font-bold text-5xl text-success">{query.title}</h1>
            <p>{query.content}</p>
            <Link href={query.backPath == undefined ? "/" : query.backPath as string} className="btn btn-primary rounded-box">Back</Link>
          </div>
        </div>
      </div>
  </>
  )
}

export default Success
