import dynamic from "next/dynamic";
import Head from "next/head";
import Footer from "~/components/Information/Footer";
import Navbar from "~/components/Nav";

const Dynamap = dynamic(() => import("~/components/BuffaloMap/dynamicMap"), {
  ssr: false,
});

const BuffaloMap = () => {
  return (
    <>
      <Head>
        <title>สมาคมอนุรักษ์ และพัฒนาควายไทย</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div
        id="map"
        className="flex min-h-screen w-full flex-col items-center justify-center bg-slate-800"
      >
        <div className="py-3 text-3xl font-bold text-white">Buffalo Map</div>
        <Dynamap />
      </div>
      <Footer />
    </>
  );
};

export default BuffaloMap;
