import Head from "next/head";
import MemberListTable from "~/components/MemberList/MemberListTable";
import Navbar from "~/components/Nav";

const MemberList = () => {
  return (
    <>
      <Head>
        <title>สมาคมอนุรักษ์ และพัฒนาควายไทย</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div
        className="flex flex-col justify-center pt-[80px]"
        style={{ fontFamily: "Kanit" }}
      >
        <MemberListTable />
      </div>
    </>
  );
};

export default MemberList;
