import Head from "next/head";
import Navbar from "~/components/Nav";

const Member = () => {
  return (
    <>
      <Head>
        <title>สมาคมอนุรักษ์ และพัฒนาควายไทย</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </>
  );
};

export default Member;
