import Head from "next/head";
import Navbar from "~/components/Nav";
import { api } from "~/utils/api";
import { GrSearch } from "react-icons/gr";
import { useEffect, useState } from "react";

const MemberList = () => {
  const [currentPage, setCurrentPage] = useState<number>(0);
  const [totalPages, setTotalPages] = useState<number>(0);
  const { data, isLoading, refetch } = api.user.getActiveUsers.useQuery({
    page: currentPage,
  });

  useEffect(() => {
    setTotalPages(data?.totalPages as number);
  }, [isLoading]);

  useEffect(() => {
    void refetch();
  }, [currentPage]);

  function handleNextPage() {
    if (currentPage < totalPages) {
      setCurrentPage(currentPage + 1);
    }
  }

  function handlePrevPage() {
    if (currentPage > 0) {
      setCurrentPage(currentPage - 1);
    } else if (currentPage <= 0) {
      setCurrentPage(0);
    }
  }

  return (
    <>
      <Head>
        <title>สมาคมอนุรักษ์ และพัฒนาควายไทย</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div
        className="flex flex-col justify-center pt-[120px]"
        style={{ fontFamily: "Kanit" }}
      >
        <div className="grid min-h-screen w-full grid-cols-5">
          <div className="col-span-1"></div>
          <div className="col-span-3">
            <div className="flex justify-between gap-2">
              <h2 className="py-2 text-3xl font-bold">รายชื่อสมาชิก</h2>
              <div className="flex items-center gap-2">
                <span className="text-xl font-bold">ค้นหา</span>
                <div className="flex gap-2">
                  <input className="bg-gray-200" type="text"></input>
                  <button type="submit">
                    <GrSearch size={30} />
                  </button>
                </div>
              </div>
            </div>
            <div className="h-[75vh] overflow-auto">
              <table className="w-full">
                <thead className="bg-gray-300">
                  <th className="px-2 py-3">no.</th>
                  <th className="px-2 py-3">wallet/member Id.</th>
                  <th className="px-2 py-3">name</th>
                  <th className="px-2 py-3">type</th>
                </thead>
                <tbody className="text-center">
                  {isLoading ? (
                    <tr>
                      <td className="px-3 py-3">
                        <span className="loading loading-spinner loading-md"></span>
                      </td>
                    </tr>
                  ) : (
                    <>
                      {data == undefined ? (
                        <tr>
                          <td className="font-bold">Empty</td>
                        </tr>
                      ) : (
                        <>
                          {data.users.map((user, index) => (
                            <tr className="hover:bg-gray-100" key={index}>
                              <td className="px-1 py-2">{index + 1}</td>
                              <td>{`${user.wallet.slice(
                                0,
                                5
                              )}...${user.wallet.slice(37)}`}</td>
                              <td className="px-1 py-2">{user.name}</td>
                              <td className="px-1 py-2">
                                {user.payment.length <= 0 ? (
                                  <>N/A</>
                                ) : (
                                  <>
                                    {user.payment[0]?.isLifeTime ? (
                                      <div className="px-1 py-2">ตลอดชีพ</div>
                                    ) : (
                                      <div className="px-1 py-2">รายปี</div>
                                    )}
                                  </>
                                )}
                              </td>
                            </tr>
                          ))}
                        </>
                      )}
                    </>
                  )}
                </tbody>
              </table>
            </div>

            <div className="flex justify-end py-3">
              <div className="join">
                <button className="join-item btn" onClick={handlePrevPage}>
                  {"<<"}
                </button>
                <button className="join-item btn">{`Page ${
                  currentPage + 1
                }`}</button>
                <button className="join-item btn" onClick={handleNextPage}>
                  {">>"}
                </button>
              </div>
            </div>
          </div>
          <div className="col-span-1"></div>
        </div>
      </div>
    </>
  );
};

export default MemberList;
