import Head from "next/head";
import Footer from "~/components/Information/Footer";
import Navbar from "~/components/Nav";

const Register = () => {
  return (
    <>
      <Head>
        <title>สมาคมอนุรักษ์ และพัฒนาควายไทย</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="flex max-h-full min-h-[600px] justify-center bg-[url('/images/bgmain.jpg')] bg-cover text-white">
        <div className="flex flex-col items-center w768:mt-[80px] w1440:mt-[150px]">
          <div
            style={{ fontFamily: "Kanit" }}
            className="mb-2 text-[2rem] w768:text-[3rem]"
          >
            สมัครสมาชิก
          </div>
          <div className="w-full bg-white text-black">
            <form className="flex flex-col gap-3 p-10 shadow-lg">
              <div className="form-control w-full max-w-xs">
                <label className="label">
                  <span className="label-text">ชื่อ - นามสกุล</span>
                </label>
                <input
                  type="text"
                  required
                  className="input-bordered input w-full max-w-xs"
                ></input>
                <label className="label">
                  <span className="label-text-alt text-red-500">*required</span>
                </label>
              </div>
              <div className="form-control w-full max-w-xs p-2">
                <label className="label">
                  <span className="label-text">เบอร์โทรศัพท์</span>
                </label>
                <input
                  type="text"
                  required
                  className="input-bordered input w-full max-w-xs"
                ></input>
                <label className="label">
                  <span className="label-text-alt text-red-500">*required</span>
                </label>
              </div>
              <div className="form-control w-full max-w-xs p-2">
                <label className="label">
                  <span className="label-text">ที่อยู่</span>
                </label>
                <input
                  type="text"
                  placeholder=""
                  className="input-bordered input w-full max-w-xs"
                ></input>
                <label className="label">
                  <span className="label-text-alt text-red-500">*required</span>
                </label>
              </div>
              <div className="form-control w-full max-w-xs p-2">
                <label className="label">
                  <span className="label-text">Bitkub Next</span>
                </label>
                <input
                  type="text"
                  required
                  disabled={true}
                  value="0x1234"
                  className="input-bordered input w-full max-w-xs"
                ></input>
              </div>
              <div className="form-control w-full max-w-xs p-2">
                <label className="label">
                  <span className="label-text">ตัวเลือกสมาชิก</span>
                </label>
                <select className="select-bordered select" required>
                  <option disabled selected>
                    เลือก
                  </option>
                  <option>รายปี 100 บาท</option>
                  <option>ตลอดชีพ 600 บาท</option>
                </select>
                <label className="label">
                  <span className="label-text-alt text-red-500">*required</span>
                </label>
              </div>
              <div>
                <div>หมายเลขบัญชีสมาคม</div>
                <div className="bg-slate-200 p-2">
                  <div>ธนาคารxxxx</div>
                  <div>เลขที่บัญชีxxxxxxxxxx</div>
                  <div>ชื่อบัญชีxxxxx xxxxxxx</div>
                </div>
              </div>
              <div className="form-control w-full max-w-xs">
                <label className="label">
                  <span className="label-text">แนบสลิป</span>
                </label>
                <input
                  type="file"
                  required
                  className="file-input-bordered file-input w-full max-w-xs"
                />
                <label className="label">
                  <span className="label-text-alt text-red-500">*required</span>
                </label>
              </div>
              <button className="btn" type="submit">
                แจ้งชำระเงิน
              </button>
            </form>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default Register;
