import { useBitkubNext } from "~/contexts/bitkubNextContext";
import { api } from "../../utils/api";
import Footer from "~/components/Information/Footer";
import Navbar from "~/components/Nav";
import Head from "next/head";
import { useEffect, useState } from "react";
import ApprovementDashBoard from "~/components/Dashboard/Dashboard";
import Unauthurized from "~/components/Shared/Unauthorized";
import { useRouter } from "next/router";
import { useIsAdmin } from "~/blockchain/MemberNFT/read";

const Approvement = () => {
  const [isAdmin, setIsAdmin] = useState<boolean>(false);
  const { isConnected } = useBitkubNext();
  const { replace } = useRouter();

  const { admin, isSuccess: adminOK, isError: adminErr } = useIsAdmin();

  useEffect(() => {
    if (isConnected) {
      if (admin && adminOK) {
        setIsAdmin(true);
      } else {
        setIsAdmin(false);
        void replace("/");
      }
    }
    if (!isConnected) void replace("/");
  }, [isAdmin, admin, isConnected, adminOK, adminErr]);

  if (!isAdmin) {
    return (
      <>
        <Unauthurized message="กำลังกลับไปหน้าหลัก.." />
      </>
    );
  }

  if (!isConnected) {
    return (
      <>
        <Unauthurized message="กำลังกลับไปหน้าหลัก.." />
      </>
    );
  }

  return (
    <>
      <Head>
        <title>สมาคมอนุรักษ์ และพัฒนาควายไทย</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <ApprovementDashBoard />
      <Footer />
    </>
  );
};

export default Approvement;
